# Get all posts
GET http://localhost:3001/api/posts  HTTP/1.1

###

# Get posts with filter

GET http://localhost:3001/api/posts?limit=3&sortDirection=desc&page=1&search=text  HTTP/1.1

###

# Get posts with filter 2

GET http://localhost:3001/api/posts?limit=3&sortDirection=asc&page=1&sortOption=Likes HTTP/1.1

###

# Get posts with filter 3

GET http://localhost:3001/api/posts?limit=3&sortDirection=desc&page=1&userId=663362521895e601eb7e41c1 HTTP/1.1

###

# Get post by id
GET http://localhost:3001/api/posts/c3fd591f-c1aa-4340-a995-93d7d4b259e7 HTTP/1.1

###

# Create a new post 1 text
POST http://localhost:3001/api/posts HTTP/1.1
Content-Type: application/json

{
  "userId": "663362521895e601eb7e41c1",
  "title": "Some text Some text Some text Some text",
  "typePost": "text",
  "announcementPublic": "announcementPublic announcementPublic announcementPublic announcementPublic announcementPublic announcementPublic",
  "textPublic": "textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic",
  "tags":["asd"]
}

###

# Create a new post 2 quote
POST http://localhost:3001/api/posts HTTP/1.1
Content-Type: application/json

{
  "userId": "663362521895e601eb7e41c1",
  "title": "Some quote Some quote Some quote Some quote",
  "typePost": "quote",
  "textQuote": "textQuote textQuote textQuote textQuote textQuote textQuote",
  "quoteAuthor": "quoteAuthor",
  "tags":["quote","some"]
}

###

# Create a new post 3 link
POST http://localhost:3001/api/posts HTTP/1.1
Content-Type: application/json

{
  "userId": "663362521895e601eb7e41c1",
  "title": "Some link Some link Some link Some link",
  "typePost": "link",
  "link": "http://localhost:3001/api/posts",
  "linkDescription": "",
  "tags":["link","some"],
  "isPublished":false
}

###

# Delete the post by id
DELETE http://localhost:3001/api/posts/7c16003f-31b5-42a6-a0d7-77d73f2a9dfe HTTP/1.1

###

# Update post by id
PATCH http://localhost:3001/api/posts/1c2bc357-9d4f-4086-a6cb-6f7c5e59657c HTTP/1.1
Content-Type: application/json

{
  "title": "Some new Some new Some new Some new"
}

###

# Like post by id
POST http://localhost:3001/api/posts/c3fd591f-c1aa-4340-a995-93d7d4b259e7/likes HTTP/1.1
Content-Type: application/json

{
  "isLike": true,
  "userId": "663362521895e601eb7e41c1"
}

###

# Repost post by id
POST http://localhost:3001/api/posts/c3fd591f-c1aa-4340-a995-93d7d4b259e7/reposts HTTP/1.1
Content-Type: application/json

{
  "isRepost": true,
  "userId": "663362521895e601eb7e41c1"
}

###
