@PORT = 3001

###

# Get all posts
GET http://localhost:{{PORT}}/api/posts  HTTP/1.1

###

# Get posts with filter

GET http://localhost:{{PORT}}/api/posts?limit=3&sortDirection=desc&page=1&search=text  HTTP/1.1

###

# Get posts with filter 2

GET http://localhost:{{PORT}}/api/posts?limit=3&sortDirection=asc&page=1&sortOption=Likes HTTP/1.1

###

# Get posts with filter 3

GET http://localhost:{{PORT}}/api/posts?limit=3&sortDirection=desc&page=1&userId=663362521895e601eb7e41c1 HTTP/1.1

###

# Get post by id
GET http://localhost:{{PORT}}/api/posts/93ec8d33-2cb5-4401-a965-64e761816866 HTTP/1.1

###

# Create a new post 1 text
POST http://localhost:{{PORT}}/api/posts HTTP/1.1
Content-Type: application/json

{
  "userId": "663362521895e601eb7e41c1",
  "title": "Some text Some text Some text Some text",
  "typePost": "text",
  "announcementPublic": "announcementPublic announcementPublic announcementPublic announcementPublic announcementPublic announcementPublic",
  "textPublic": "textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic",
  "tags":["asd"]
}

###

# Create a new post 2 quote
POST http://localhost:{{PORT}}/api/posts HTTP/1.1
Content-Type: application/json

{
  "userId": "663362521895e601eb7e41c1",
  "title": "Some quote Some quote Some quote Some quote",
  "typePost": "quote",
  "textQuote": "textQuote textQuote textQuote textQuote textQuote textQuote",
  "quoteAuthor": "quoteAuthor",
  "tags":["quote","some"]
}

###

# Create a new post 3 link
POST http://localhost:{{PORT}}/api/posts HTTP/1.1
Content-Type: application/json

{
  "userId": "663362521895e601eb7e41c1",
  "title": "Some link Some link Some link Some link",
  "typePost": "link",
  "link": "https://htmlacademy.ru",
  "linkDescription": "",
  "tags":["link","some"],
  "isPublished":false
}

###

# Create a new post 4 video
POST http://localhost:{{PORT}}/api/posts HTTP/1.1
Content-Type: application/json

{
  "userId": "663362521895e601eb7e41c1",
  "title": "Some video Some video Some video Some video",
  "typePost": "video",
  "videoUrl": "https://www.youtube.com/watch",
  "tags":["video","some"]
}

###

# Delete the post by id
DELETE http://localhost:{{PORT}}/api/posts/7c16003f-31b5-42a6-a0d7-77d73f2a9dfe HTTP/1.1

###

# Update post by id
PATCH http://localhost:{{PORT}}/api/posts/453ee77d-9a21-4b10-84a0-dd5c3170de4c HTTP/1.1
Content-Type: application/json

{
  "title": "Some new quote Some new quote Some new quote"
}

###

# Like post by id
PUT http://localhost:{{PORT}}/api/posts/453ee77d-9a21-4b10-84a0-dd5c3170de4c/likes HTTP/1.1
Content-Type: application/json

{
  "isLike": false,
  "userId": "663362521895e601eb7e41c1"
}

###

# Repost post by id
POST http://localhost:{{PORT}}/api/posts/453ee77d-9a21-4b10-84a0-dd5c3170de4c/reposts HTTP/1.1
Content-Type: application/json

{
  "userId": "663362521895e601eb7e41c1"
}

###


# Получить статистику по постам
GET http://localhost:{{PORT}}/api/posts/663362521895e601eb7e41c1/statistics HTTP/1.1

###
