@PORT = 3004

# USERS
###

# Create a new user
POST http://localhost:{{PORT}}/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "example1@email.ru",
  "firstName": "Mikhail",
  "lastName": "Yanov",
  "password": "123456"
}

###

# Login
POST http://localhost:{{PORT}}/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "example@email.ru",
  "password": "123456"
}

###

# Изменить пароль
PATCH http://localhost:{{PORT}}/api/users/new-password HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMzNjI1MjE4OTVlNjAxZWI3ZTQxYzEiLCJlbWFpbCI6ImV4YW1wbGVAZW1haWwucnUiLCJmaXJzdE5hbWUiOiJNaWtoYWlsIiwibGFzdE5hbWUiOiJZYW5vdiIsImlhdCI6MTcxNTA2ODYwNCwiZXhwIjoxNzE1MjQxNDA0fQ.HPUsshGhA4kmfzBqmX6g9a5pXWo0CKuDN1lcqe5-q64

{
  "password": "123456",
  "newPassword": "1234567"
}

###

# Get new JWT pair
POST http://localhost:{{PORT}}/api/users/refresh HTTP/1.1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMzNjI1MjE4OTVlNjAxZWI3ZTQxYzEiLCJlbWFpbCI6ImV4YW1wbGVAZW1haWwucnUiLCJmaXJzdE5hbWUiOiJNaWtoYWlsIiwibGFzdE5hbWUiOiJZYW5vdiIsInRva2VuSWQiOiJiYTcyOTE0OS01NzllLTRkMTctYmFjMS1iODI1ZWQxNjIyOTQiLCJpYXQiOjE3MTUwNjYzMjMsImV4cCI6MTcxNzY1ODMyM30.Mo_RZKJWKPE_SLXYr0cGN7bqzsPBrbxiuBfTrHuuCU4

###

# Get user by ID
GET http://localhost:{{PORT}}/api/users/663362521895e601eb7e41c1 HTTP/1.1


# POSTS
###

# Create a new post 1 text
POST http://localhost:{{PORT}}/api/blog HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMzNjI1MjE4OTVlNjAxZWI3ZTQxYzEiLCJlbWFpbCI6ImV4YW1wbGVAZW1haWwucnUiLCJmaXJzdE5hbWUiOiJNaWtoYWlsIiwibGFzdE5hbWUiOiJZYW5vdiIsImlhdCI6MTcxNTA2ODYwNCwiZXhwIjoxNzE1MjQxNDA0fQ.HPUsshGhA4kmfzBqmX6g9a5pXWo0CKuDN1lcqe5-q64

{
  "title": "Проверка text Проверка text Проверка text",
  "typePost": "text",
  "announcementPublic": "announcementPublic announcementPublic announcementPublic announcementPublic announcementPublic announcementPublic",
  "textPublic": "textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic textPublic",
  "tags":["tagtext"]
}

###

# Create a new post 2 quote
POST http://localhost:{{PORT}}/api/blog HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMzNjI1MjE4OTVlNjAxZWI3ZTQxYzEiLCJlbWFpbCI6ImV4YW1wbGVAZW1haWwucnUiLCJmaXJzdE5hbWUiOiJNaWtoYWlsIiwibGFzdE5hbWUiOiJZYW5vdiIsImlhdCI6MTcxNTA2ODYwNCwiZXhwIjoxNzE1MjQxNDA0fQ.HPUsshGhA4kmfzBqmX6g9a5pXWo0CKuDN1lcqe5-q64

{
  "title": "Some quote Some quote Some quote Some quote",
  "typePost": "quote",
  "textQuote": "textQuote textQuote textQuote textQuote textQuote textQuote",
  "quoteAuthor": "quoteAuthor",
  "tags":["quote","some"]
}

###

# Create a new post 3 link
POST http://localhost:{{PORT}}/api/blog HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMzNjI1MjE4OTVlNjAxZWI3ZTQxYzEiLCJlbWFpbCI6ImV4YW1wbGVAZW1haWwucnUiLCJmaXJzdE5hbWUiOiJNaWtoYWlsIiwibGFzdE5hbWUiOiJZYW5vdiIsImlhdCI6MTcxNTA2ODYwNCwiZXhwIjoxNzE1MjQxNDA0fQ.HPUsshGhA4kmfzBqmX6g9a5pXWo0CKuDN1lcqe5-q64

{
  "title": "Some link Some link Some link Some link",
  "typePost": "link",
  "link": "https://htmlacademy.ru",
  "linkDescription": "",
  "tags":["link","some"]
}

###

# Create a new post 4 video
POST http://localhost:{{PORT}}/api/blog HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMzNjI1MjE4OTVlNjAxZWI3ZTQxYzEiLCJlbWFpbCI6ImV4YW1wbGVAZW1haWwucnUiLCJmaXJzdE5hbWUiOiJNaWtoYWlsIiwibGFzdE5hbWUiOiJZYW5vdiIsImlhdCI6MTcxNTA2ODYwNCwiZXhwIjoxNzE1MjQxNDA0fQ.HPUsshGhA4kmfzBqmX6g9a5pXWo0CKuDN1lcqe5-q64

{
  "title": "Some video Some video Some video Some video",
  "typePost": "video",
  "videoUrl": "https://www.youtube.com/watch",
  "tags":["video","some"]
}

###

# Get all posts
GET http://localhost:{{PORT}}/api/blog  HTTP/1.1

###
