# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "example@email.ru",
  "firstName": "Mikhail",
  "lastName": "Yanov",
  "password": "123456"
}

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "example@email.ru",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/663362521895e601eb7e41c1 HTTP/1.1

###

# Изменить пароль
PATCH http://localhost:3000/api/auth/663362521895e601eb7e41c1/new-password HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMzNjI1MjE4OTVlNjAxZWI3ZTQxYzEiLCJlbWFpbCI6ImV4YW1wbGVAZW1haWwucnUiLCJmaXJzdE5hbWUiOiJNaWtoYWlsIiwibGFzdE5hbWUiOiJZYW5vdiIsImlhdCI6MTcxNTA2NzI5MCwiZXhwIjoxNzE1MjQwMDkwfQ.hjd7k4099EwfbB3XB1VkSjS0dLqURB7NL3y2B4mUK4A

{
  "password": "1234567",
  "newPassword": "123456"
}

###

# Get new JWT pair
POST http://localhost:3000/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMzNjI1MjE4OTVlNjAxZWI3ZTQxYzEiLCJlbWFpbCI6ImV4YW1wbGVAZW1haWwucnUiLCJmaXJzdE5hbWUiOiJNaWtoYWlsIiwibGFzdE5hbWUiOiJZYW5vdiIsImlhdCI6MTcxNDc0NDUwOSwiZXhwIjoxNzE3MzM2NTA5fQ.JMtsdn16OeqakHQ84wHx1tca4rP4B78qZagejpvt8Q8


###

# Check user token
POST http://localhost:3000/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjMzNjI1MjE4OTVlNjAxZWI3ZTQxYzEiLCJlbWFpbCI6ImV4YW1wbGVAZW1haWwucnUiLCJmaXJzdE5hbWUiOiJNaWtoYWlsIiwibGFzdE5hbWUiOiJZYW5vdiIsImlhdCI6MTcxNDk4ODM5NSwiZXhwIjoxNzE1MTYxMTk1fQ.ueyPrKgHA-pATnKcn_YgAFxZmknYRiJsnPJRonryT_M

###

# Demo route for Pipe
GET http://localhost:3000/api/auth/demo/1 HTTP/1.1.
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJlbWFpbCI6ImV4YW1wbGVAZW1haWwucnUiLCJmaXJzdE5hbWUiOiJNaWtoYWlsIiwibGFzdE5hbWUiOiJZYW5vdiIsImlhdCI6MTcxMzg5ODQ3MCwiZXhwIjoxNzEzODk4NzcwfQ.dHBysC0IIxCaeKQ6zM5lXylbRB4VdMb0__VcUGl9mL8

###
