# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "example@email.ru",
  "firstName": "Mikhail",
  "lastName": "Yanov",
  "password": "123456"
}


###

# Get user by ID
GET http://localhost:3000/api/auth/d45dc925-bbb2-455f-8a07-ff5ca27674a0 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "example@email.ru",
  "password": "123456"
}

###
